---
# microk8s join cluster
- name: Copy join script
  ansible.builtin.copy:
    src: "./.ignore.{{ inventory_hostname }}.sh"
    dest: "./{{ inventory_hostname }}.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags:
  - clustering
  - follower
  - join

- name: Execute microk8s join token
  shell:
    cmd: "./{{ inventory_hostname }}.sh"
  register: result
  tags:
  - clustering
  - follower
  - join

- name: Print return information from the previous task
  ansible.builtin.debug:
    msg: "{{ result }}"
  tags:
  - clustering
  - follower
  - join