---
- name: Append microk8s group to list of users
  ansible.builtin.user:
    name: "{{ item.user_id }}"
    shell: "{{ item.user_shell }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{  microk8s_users  }}"

- name: reset ssh connection to refresh group
  meta: reset_connection

- name: Generate kubeconfig
  ansible.builtin.command:
    cmd: microk8s config
  register: kubeconfig

- name: Write file to home directory
  copy:
      dest: "./{{ kubeconfig }}"
      content: |
        {{ kubeconfig.stdout }}

- name: Copy file from remote to local
  ansible.builtin.fetch:
    src: "./{{ kubeconfig }}"
    dest: "./.ignore.{{ kubeconfig }}"
    flat: yes
    