---
- name: Append microk8s group to list of users
  ansible.builtin.user:
    name: "{{ item.user_id }}"
    shell: "{{ item.user_shell }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{  microk8s_users  }}"
  tags:
  - rbac

- name: Update kube config permissions
  ansible.builtin.file:
    path: "/home/{{ item.user_id }}"
    state: directory
    owner: "{{ item.user_id }}"
    group: "{{ item.user_id }}"
    recurse: yes
  loop: "{{  microk8s_users  }}"
  tags:
  - rbac

- name: reset ssh connection to refresh group
  meta: reset_connection
  tags:
  - rbac
