Vagrant.configure('2') do |config|
    # INPUT PAYLOAD
    payload_file=File.expand_path('./env.yaml')
    payload=YAML.load_file(payload_file)['esxi']

    # OS image
    config.vm.box = payload['vm']['box']

    # PLUGINS
    config.vagrant.plugins = payload['plugins']
  
    #  Use rsync and NFS synced folders. (or disable them)
    #    https://www.vagrantup.com/docs/synced-folders/
    #config.vm.synced_folder('.', '/vagrant', type: 'rsync')
    config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)

    #
    #  Provider (esxi) settings
    #
    config.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = payload['host']
  
      #  ESXi username
      #    Default is 'root'.
      esxi.esxi_username = payload['user']
      esxi.esxi_password = payload['password']
  
      #  SSH port.
      #esxi.esxi_hostport = 22
  
      #  HIGHLY RECOMMENDED!  Virtual Network
      #esxi.esxi_virtual_network = ['VM Network','VM Network2','VM Network3','VM Network4']
  
      #  OPTIONAL.  Specify a Disk Store
      #    If it's not specified, the Default is to use the least used Disk Store.
      esxi.esxi_disk_store = payload['vm']['datastore']
  
      #  OPTIONAL.  Resource Pool
      #esxi.esxi_resource_pool = '/Vagrant'
  
      #  Optional. Specify a VM to clone instead of uploading a box.
      #esxi.clone_from_vm = 'resource_pool/source_vm'
  
      #  OPTIONAL.  Guest VM name to use.
      esxi.guest_name = 'microk8s'
  
      #  OPTIONAL.  When automatically naming VMs, use this prefix.
      esxi.guest_name_prefix = 'V-'
  
      #  OPTIONAL.  Set the guest username login.  The default is 'vagrant'.
      #esxi.guest_username = 'vagrant'
  
      #  OPTIONAL.  Memory size override
      esxi.guest_memsize = payload['vm']['ram']
  
      #  OPTIONAL.  Virtual CPUs override
      esxi.guest_numvcpus = payload['vm']['vcpu']
  
      #  OPTIONAL. Specify a disk type.
      #esxi.guest_disk_type = 'thick'
  
      #  OPTIONAL. Boot disk size.
      esxi.guest_boot_disk_size = payload['vm']['disk']
  
      #  OPTIONAL.  Create additional storage for guests.
      #esxi.guest_storage = [ 10, 20, { size: 30, datastore: 'datastore1' } ]
  
      #  OPTIONAL & RISKY.  Specify up to 4 MAC addresses
      #esxi.guest_mac_address = ['00:50:56:aa:bb:cc', '00:50:56:01:01:01','00:50:56:02:02:02','00:50:56:BE:AF:01' ]
  
      #   OPTIONAL & RISKY.  Specify a guest_nic_type
      #esxi.guest_nic_type = 'e1000'
  
      #  OPTIONAL. specify snapshot options.
      #esxi.guest_snapshot_includememory = 'true'
      #esxi.guest_snapshot_quiesced = 'true'
  
      #  RISKY. guest_guestos
      #esxi.guest_guestos = 'centos-64'
  
      #  OPTIONAL. guest_virtualhw_version
      #    If unspecified, the default will be generated by the OVFTool.  Most
      #    of the time, you don't need to change this unless you are using advanced
      #    custom vmx settings that require it.
      #    ESXi 6.5 supports these versions. 4,7,8,9,10,11,12,13 & 14.
      #esxi.guest_virtualhw_version = '9'
  
      #  OPTIONAL. guest_autostart
      #esxi.guest_autostart = 'false'
  
      #  RISKY. guest_custom_vmx_settings
      #esxi.guest_custom_vmx_settings = [['vhv.enable','TRUE'], ['floppy0.present','TRUE']]
  
      #  OPTIONAL. local_lax
      #esxi.local_lax = 'true'
  
      #  OPTIONAL.  Guest IP Caching
      #esxi.local_use_ip_cache = 'False'
  
      #  DANGEROUS!  Allow Overwrite
      #esxi.local_allow_overwrite = 'True'
  
      #  Advanced users.
      #esxi.local_failonwarning = 'True'
  
      #  Plugin debug output.
      #esxi.debug = 'true'
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yaml"
      ansible.limit = "all"
    end
end
  